name: advRobCLIP
channels:
  - anaconda
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aom=3.6.0
  - asttokens=2.0.5
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=2.0.0
  - blas=1.0
  - blosc=1.21.3
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.9.24
  - certifi=2024.8.30
  - cffi=1.16.0
  - cfitsio=3.470
  - charls=2.2.0
  - charset-normalizer=2.0.4
  - colorama=0.4.4
  - comm=0.2.1
  - contourpy=1.2.0
  - cudatoolkit=11.6.2
  - cycler=0.11.0
  - dav1d=1.2.1
  - debugpy=1.6.7
  - decorator=5.1.1
  - entrypoints=0.4
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - ffmpeg=4.3
  - filelock=3.13.1
  - fonttools=4.51.0
  - freetype=2.12.1
  - fsspec=2024.3.1
  - ftfy=5.8
  - future=0.18.3
  - giflib=5.2.2
  - gmp=6.3.0
  - gnutls=3.6.13
  - huggingface_hub=0.24.6
  - imagecodecs=2023.1.23
  - imageio=2.33.1
  - intel-openmp=2021.4.0
  - ipykernel=6.28.0
  - ipython=8.20.0
  - ipython_genutils=0.2.0
  - jedi=0.18.1
  - jpeg=9e
  - jupyter_client=7.1.2
  - jupyter_core=5.5.0
  - jxrlib=1.1
  - kiwisolver=1.4.4
  - kornia=0.7.1
  - krb5=1.20.1
  - lame=3.100
  - lazy_loader=0.4
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libabseil=20240116.2
  - libaec=1.0.4
  - libavif=0.11.1
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.9.1
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=13.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=13.2.0
  - libiconv=1.17
  - libnghttp2=1.57.0
  - libpng=1.6.39
  - libprotobuf=4.25.3
  - libsodium=1.0.18
  - libssh2=1.11.0
  - libstdcxx-ng=13.2.0
  - libtiff=4.5.1
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - libzopfli=1.0.3
  - lz4-c=1.9.4
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.6
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - nettle=3.6
  - networkx=3.3
  - ninja=1.10.2
  - ninja-base=1.10.2
  - numpy=1.24.3
  - numpy-base=1.24.3
  - open-clip-torch=2.24.0
  - openai-clip=1.0.1
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.3.1
  - packaging=23.2
  - pandas=2.2.2
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.3.0
  - pip=24.0
  - platformdirs=3.10.0
  - pooch=1.7.0
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - protobuf=4.25.3
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.14.0
  - pyparsing=3.1.2
  - pysocks=1.7.1
  - python=3.10.14
  - python-dateutil=2.8.2
  - python-tzdata=2024.1
  - python_abi=3.10
  - pytorch=1.12.1
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - readline=8.2
  - regex=2023.10.3
  - safetensors=0.4.2
  - scikit-image=0.24.0
  - seaborn=0.13.2
  - sentencepiece=0.1.99
  - setuptools=69.5.1
  - six=1.16.0
  - snappy=1.2.1
  - sqlite=3.45.3
  - stack_data=0.2.0
  - tifffile=2023.4.12
  - timm=1.0.3
  - tk=8.6.14
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - tornado=6.3.3
  - tqdm=4.63.0
  - traitlets=5.7.1
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2024a
  - unicodedata2=15.1.0
  - wcwidth=0.2.10
  - wheel=0.37.1
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zfp=1.0.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - chardet==4.0.0
      - huggingface-hub==0.23.4
      - idna==2.10
      - requests==2.25.1
      - scipy==1.14.1
      - tokenizers==0.19.1
      - torchattacks==3.5.1
      - torchgeometry==0.1.2
      - transformers==4.42.3
      - urllib3==1.26.20
prefix: /home/vincenzo.derosa/.conda/envs/advRobCLIP
